### ISSUE TITLE
Building the library fails

### ISSUE THREAD

**Issue by ndelvalle** [seracio/zscore#3]
`npm run build` generates the following error:
```
> zscore@0.1.0 build /Users/ndelvalle/Projects/zscore
> babel src --out-dir dist

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:1349:5)
    at /Users/ndelvalle/Projects/zscore/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
    at /Users/ndelvalle/Projects/zscore/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/ndelvalle/Projects/zscore/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/ndelvalle/Projects/zscore/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/ndelvalle/Projects/zscore/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at /Users/ndelvalle/Projects/zscore/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
    at /Users/ndelvalle/Projects/zscore/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
```

I'm working with node `v8.11.2`

**Comment by nmondon** [comment]
#JavaScript... 
OK, I'm gonna update dependencies and engines and make a brand new build
